# Generated by Django 5.0 on 2025-11-23 05:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qr_codes', '0001_initial'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Solo letras, números y guiones bajos', regex='^[a-zA-Z0-9_]+$')])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('total_quizzes_completados', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='SesionQuiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje_obtenido', models.IntegerField(default=0)),
                ('puntaje_maximo', models.IntegerField()),
                ('tiempo_completado', models.IntegerField()),
                ('fecha_hora_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_fin', models.DateTimeField(blank=True, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('codigo_qr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to='qr_codes.codigoqr')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='quizzes.quiz')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'sesiones_quiz',
            },
        ),
    ]
