# Generated by Django 5.0 on 2025-11-23 05:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoQR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_desactivacion', models.DateTimeField(blank=True, null=True)),
                ('ubicacion_fisica', models.CharField(blank=True, max_length=200)),
                ('numero_escaneos', models.IntegerField(default=0)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigos_qr_creados', to='authentication.administrador')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_qr', to='quizzes.quiz')),
            ],
            options={
                'db_table': 'codigos_qr',
            },
        ),
    ]
